<a href="https://colab.research.google.com/github/adityarasal8-gif/NNDL-Practicals/blob/main/NNDL_Prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world

In [ ]:
import numpy as np

In [ ]:
vector1=np.array([1,2,3])
vector2=np.array([4,5,6])
print("Vector 1 = ",vector1)
print("Vector 2 = ",vector2)

Vector 1 =  [1 2 3]
Vector 2 =  [4 5 6]

In [ ]:
addition=vector1+vector2
print("Vector Addition = ",addition)

Vector Addition =  [5 7 9]

In [ ]:
multiply=np.matmul(vector1,vector2)
print("Multiplication vector 1 and 2 =",multiply)

Multiplication vector 1 and 2 = 32

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix A : ")
print(A)
print("Matrix B : ")
print(B)

Matrix A :
[[1 2]
 [3 4]]
Matrix B :
[[5 6]
 [7 8]]

In [ ]:
C=A@B
print(C)

[[19 22]
 [43 50]]

In [ ]:
C=np.matmul(A,B)
print(C)

[[19 22]
 [43 50]]

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Wine dataset.csv to Wine dataset.csv

In [ ]:
import pandas as pd
data = pd.read_csv('Wine dataset.csv')
data.head()

,class,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [ ]:
import kagglehub
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")
dataset=pd.read_csv(path+"/creditcard.csv")
dataset.head()

Using Colab cache for faster access to the 'creditcardfraud' dataset.

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0